# Generated by Django 4.1.4 on 2022-12-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_toppost'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Turi: ')),
                ('content', models.TextField(verbose_name='Malumoti: ')),
                ('use', models.CharField(max_length=20, verbose_name='Ismi: ')),
                ('categories', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img1', models.CharField(max_length=255, verbose_name='Rasm: ')),
                ('img2', models.CharField(max_length=255, verbose_name='Rasm:')),
            ],
        ),
    ]
