# Generated by Django 4.1.4 on 2022-12-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_mainpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi1', models.CharField(max_length=20)),
                ('turi2', models.CharField(max_length=20)),
                ('turi3', models.CharField(max_length=20)),
                ('turi4', models.CharField(max_length=20)),
                ('turi5', models.CharField(max_length=20)),
                ('soni1', models.IntegerField(default=1)),
                ('soni2', models.IntegerField(default=1)),
                ('soni3', models.IntegerField(default=1)),
                ('soni4', models.IntegerField(default=1)),
                ('soni5', models.IntegerField(default=1)),
            ],
        ),
    ]
